// =====================================================
// SUPERADMIN / ADMIN PERMISSION SYSTEM
// =====================================================

const currentRole =
    String(
        sessionStorage.getItem("adminRole") || ""
    )
    .trim()
    .toLowerCase();

const currentUsername =
    String(
        sessionStorage.getItem("adminUsername") || ""
    )
    .trim()
    .toLowerCase();


// -----------------------------------------------------
// SUPERADMIN CHECK
// -----------------------------------------------------

const isSuperAdmin =
    currentRole === "superadmin" ||
    currentRole === "super_admin" ||
    currentRole === "super admin" ||
    currentUsername === "superadmin";


console.log("=================================");
console.log("ADMIN PERMISSION CHECK");
console.log("Username:", currentUsername);
console.log("Role:", currentRole);
console.log("Is Superadmin:", isSuperAdmin);
console.log("=================================");


// =====================================================
// APPLY PERMISSIONS
// =====================================================

function applyPermissions() {

    const protectedItems =
        document.querySelectorAll(
            ".superadmin-only"
        );


    const protectedCards =
        document.querySelectorAll(
            ".superadmin-card"
        );


    // =================================================
    // SUPERADMIN
    // =================================================

    if (isSuperAdmin) {

        console.log(
            "✅ SUPERADMIN ACCESS ENABLED"
        );


        protectedItems.forEach(
            item => {

                // Remove locked classes
                item.classList.remove(
                    "locked"
                );

                item.classList.remove(
                    "disabled"
                );

                item.classList.remove(
                    "restricted"
                );


                // Remove disabled attributes
                item.removeAttribute(
                    "aria-disabled"
                );

                item.removeAttribute(
                    "disabled"
                );


                // Enable pointer
                item.style.pointerEvents =
                    "auto";

                item.style.cursor =
                    "pointer";

                item.style.opacity =
                    "1";


                // Remove ANY JS lock
                item
                    .querySelectorAll(
                        ".js-lock-icon"
                    )
                    .forEach(
                        lock =>
                            lock.remove()
                    );


                // Remove lock text generated by JS
                item
                    .querySelectorAll(
                        ".lock-icon"
                    )
                    .forEach(
                        lock =>
                            lock.remove()
                    );


                // Remove old click blockers
                item.onclick =
                    null;

            }
        );


        protectedCards.forEach(
            card => {

                card.classList.remove(
                    "locked"
                );

                card.classList.remove(
                    "disabled"
                );

                card.classList.remove(
                    "restricted"
                );


                card.style.pointerEvents =
                    "auto";

                card.style.opacity =
                    "1";


                card
                    .querySelectorAll(
                        ".js-lock-icon"
                    )
                    .forEach(
                        lock =>
                            lock.remove()
                    );

            }
        );


        return;

    }


    // =================================================
    // NORMAL ADMIN
    // =================================================

    console.log(
        "🔒 NORMAL ADMIN RESTRICTIONS ENABLED"
    );


    protectedItems.forEach(
        item => {

            item.classList.add(
                "locked"
            );


            item.setAttribute(
                "aria-disabled",
                "true"
            );


            item.style.cursor =
                "not-allowed";


            item.style.opacity =
                "0.65";


            // Don't allow normal navigation
            item.addEventListener(
                "click",
                blockRestrictedClick,
                true
            );


            // Add ONE lock
            if (
                !item.querySelector(
                    ".js-lock-icon"
                )
            ) {

                const lock =
                    document.createElement(
                        "span"
                    );


                lock.className =
                    "js-lock-icon";


                lock.textContent =
                    "🔒";


                lock.style.marginLeft =
                    "auto";


                item.appendChild(
                    lock
                );

            }

        }
    );


    protectedCards.forEach(
        card => {

            card.classList.add(
                "locked"
            );


            card.style.cursor =
                "not-allowed";


            card.style.opacity =
                "0.65";


            const link =
                card.querySelector(
                    "a"
                );


            if (
                link
            ) {

                link.addEventListener(
                    "click",
                    blockRestrictedClick,
                    true
                );

            }

        }
    );

}


// =====================================================
// BLOCK RESTRICTED CLICK
// =====================================================

function blockRestrictedClick(
    event
) {

    event.preventDefault();

    event.stopPropagation();

    event.stopImmediatePropagation();


    showAccessRestricted();

    return false;

}


// =====================================================
// ACCESS MESSAGE
// =====================================================

function showAccessRestricted() {

    const existing =
        document.getElementById(
            "accessRestrictedMessage"
        );


    if (
        existing
    ) {

        existing.remove();

    }


    const box =
        document.createElement(
            "div"
        );


    box.id =
        "accessRestrictedMessage";


    box.innerHTML = `

        <div class="access-message-inner">

            <div class="access-message-icon">
                🔒
            </div>

            <div class="access-message-content">

                <strong>
                    Access Restricted
                </strong>

                <span>
                    This section is available
                    only to Super Administrators.
                </span>

            </div>

            <button
                type="button"
                id="closeAccessMessage"
            >
                ×
            </button>

        </div>

    `;


    document.body.appendChild(
        box
    );


    const close =
        document.getElementById(
            "closeAccessMessage"
        );


    if (
        close
    ) {

        close.addEventListener(
            "click",
            () => {

                box.remove();

            }
        );

    }


    setTimeout(
        () => {

            if (
                box &&
                box.parentNode
            ) {

                box.remove();

            }

        },
        4000
    );

}


// =====================================================
// RUN AFTER PAGE LOAD
// =====================================================

if (
    document.readyState ===
    "loading"
) {

    document.addEventListener(
        "DOMContentLoaded",
        applyPermissions
    );

}
else {

    applyPermissions();

}
